// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  taskId: __t.option(__t.u64()),
  nodeId: __t.option(__t.u64()),
  outputType: __t.string(),
  summary: __t.string(),
  details: __t.string(),
  linksJson: __t.string(),
  urgency: __t.string(),
  suggestedNodeTitle: __t.string(),
  suggestedNodeSummary: __t.string(),
};
