// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workerId: __t.u64().primaryKey().name("worker_id"),
  roomId: __t.u64().name("room_id"),
  name: __t.string(),
  persona: __t.string(),
  status: __t.string(),
  detail: __t.string(),
  currentTaskId: __t.option(__t.u64()).name("current_task_id"),
  currentNodeId: __t.option(__t.u64()).name("current_node_id"),
  completedCount: __t.u32().name("completed_count"),
  updatedAt: __t.timestamp().name("updated_at"),
});
