// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  outputId: __t.u64().primaryKey().name("output_id"),
  roomId: __t.u64().name("room_id"),
  taskId: __t.option(__t.u64()).name("task_id"),
  nodeId: __t.option(__t.u64()).name("node_id"),
  outputType: __t.string().name("output_type"),
  summary: __t.string(),
  details: __t.string(),
  linksJson: __t.string().name("links_json"),
  urgency: __t.string(),
  suggestedNodeTitle: __t.string().name("suggested_node_title"),
  suggestedNodeSummary: __t.string().name("suggested_node_summary"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
