// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  taskId: __t.u64().primaryKey().name("task_id"),
  roomId: __t.u64().name("room_id"),
  nodeId: __t.option(__t.u64()).name("node_id"),
  taskType: __t.string().name("task_type"),
  instructions: __t.string(),
  status: __t.string(),
  priority: __t.u32(),
  resultSummary: __t.string().name("result_summary"),
  createdBy: __t.identity().name("created_by"),
  claimedBy: __t.option(__t.identity()).name("claimed_by"),
  createdAt: __t.timestamp().name("created_at"),
  claimedAt: __t.option(__t.timestamp()).name("claimed_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
