// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  title: __t.string(),
  summary: __t.string(),
  nodeType: __t.string(),
  source: __t.string(),
  urgency: __t.string(),
  sourceRefId: __t.option(__t.u64()),
  x: __t.f64(),
  y: __t.f64(),
};
