// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.u64().primaryKey().name("node_id"),
  roomId: __t.u64().name("room_id"),
  title: __t.string(),
  summary: __t.string(),
  nodeType: __t.string().name("node_type"),
  source: __t.string(),
  urgency: __t.string(),
  sourceRefId: __t.option(__t.u64()).name("source_ref_id"),
  x: __t.f64(),
  y: __t.f64(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
