// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  edgeId: __t.u64().primaryKey().name("edge_id"),
  roomId: __t.u64().name("room_id"),
  fromNodeId: __t.u64().name("from_node_id"),
  toNodeId: __t.u64().name("to_node_id"),
  label: __t.string(),
  edgeType: __t.string().name("edge_type"),
  strength: __t.f32(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
