// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.u64().primaryKey().name("node_id"),
  roomId: __t.u64().name("room_id"),
  agentKind: __t.string().name("agent_kind"),
  agentState: __t.string().name("agent_state"),
  insight: __t.string(),
  linksJson: __t.string().name("links_json"),
  confidence: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
