// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questionId: __t.u64().primaryKey().name("question_id"),
  roomId: __t.u64().name("room_id"),
  nodeId: __t.option(__t.u64()).name("node_id"),
  question: __t.string(),
  source: __t.string(),
  urgency: __t.string(),
  status: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
