// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  roomId: __t.u64(),
  kind: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  connectedTo: __t.option(__t.string()),
  urgency: __t.string(),
  question: __t.option(__t.string()),
  task: __t.option(__t.string()),
  confidence: __t.option(__t.f64()),
};
