// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  roomId: __t.u64().name("room_id"),
  eventType: __t.string().name("event_type"),
  message: __t.string(),
  nodeId: __t.option(__t.u64()).name("node_id"),
  taskId: __t.option(__t.u64()).name("task_id"),
  actor: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
});
