// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  nodeId: __t.u64(),
  roomId: __t.u64(),
  agentKind: __t.string(),
  agentState: __t.string(),
  insight: __t.string(),
  linksJson: __t.string(),
  confidence: __t.string(),
};
