// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkId: __t.u64().primaryKey().name("chunk_id"),
  roomId: __t.u64().name("room_id"),
  source: __t.string(),
  text: __t.string(),
  startMs: __t.u64().name("start_ms"),
  endMs: __t.u64().name("end_ms"),
  sourceParticipantId: __t.option(__t.u64()).name("source_participant_id"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
});
