// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentOutput = __t.object("AgentOutput", {
  outputId: __t.u64(),
  roomId: __t.u64(),
  taskId: __t.option(__t.u64()),
  nodeId: __t.option(__t.u64()),
  outputType: __t.string(),
  summary: __t.string(),
  details: __t.string(),
  linksJson: __t.string(),
  urgency: __t.string(),
  suggestedNodeTitle: __t.string(),
  suggestedNodeSummary: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AgentOutput = __Infer<typeof AgentOutput>;

export const AgentTask = __t.object("AgentTask", {
  taskId: __t.u64(),
  roomId: __t.u64(),
  nodeId: __t.option(__t.u64()),
  taskType: __t.string(),
  instructions: __t.string(),
  status: __t.string(),
  priority: __t.u32(),
  resultSummary: __t.string(),
  createdBy: __t.identity(),
  claimedBy: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
  claimedAt: __t.option(__t.timestamp()),
  completedAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type AgentTask = __Infer<typeof AgentTask>;

export const Finding = __t.object("Finding", {
  findingId: __t.u64(),
  roomId: __t.u64(),
  nodeId: __t.option(__t.u64()),
  outputId: __t.option(__t.u64()),
  title: __t.string(),
  summary: __t.string(),
  linksJson: __t.string(),
  urgency: __t.string(),
  status: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Finding = __Infer<typeof Finding>;

export const MapEdge = __t.object("MapEdge", {
  edgeId: __t.u64(),
  roomId: __t.u64(),
  fromNodeId: __t.u64(),
  toNodeId: __t.u64(),
  label: __t.string(),
  edgeType: __t.string(),
  strength: __t.f32(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type MapEdge = __Infer<typeof MapEdge>;

export const MapNode = __t.object("MapNode", {
  nodeId: __t.u64(),
  roomId: __t.u64(),
  title: __t.string(),
  summary: __t.string(),
  nodeType: __t.string(),
  source: __t.string(),
  urgency: __t.string(),
  sourceRefId: __t.option(__t.u64()),
  x: __t.f64(),
  y: __t.f64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MapNode = __Infer<typeof MapNode>;

export const Participant = __t.object("Participant", {
  participantId: __t.u64(),
  roomId: __t.u64(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  status: __t.string(),
  cursorNodeId: __t.option(__t.u64()),
  joinedAt: __t.timestamp(),
  lastSeenAt: __t.timestamp(),
});
export type Participant = __Infer<typeof Participant>;

export const QuestionCandidate = __t.object("QuestionCandidate", {
  questionId: __t.u64(),
  roomId: __t.u64(),
  nodeId: __t.option(__t.u64()),
  question: __t.string(),
  source: __t.string(),
  urgency: __t.string(),
  status: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAt: __t.option(__t.timestamp()),
});
export type QuestionCandidate = __Infer<typeof QuestionCandidate>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  code: __t.string(),
  title: __t.string(),
  description: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomEvent = __t.object("RoomEvent", {
  eventId: __t.u64(),
  roomId: __t.u64(),
  eventType: __t.string(),
  message: __t.string(),
  nodeId: __t.option(__t.u64()),
  taskId: __t.option(__t.u64()),
  actor: __t.identity(),
  createdAt: __t.timestamp(),
});
export type RoomEvent = __Infer<typeof RoomEvent>;

export const RoomFocus = __t.object("RoomFocus", {
  roomId: __t.u64(),
  nodeId: __t.option(__t.u64()),
  label: __t.string(),
  setBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type RoomFocus = __Infer<typeof RoomFocus>;

export const SharedNote = __t.object("SharedNote", {
  noteId: __t.u64(),
  roomId: __t.u64(),
  nodeId: __t.option(__t.u64()),
  body: __t.string(),
  sourceDisplayName: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type SharedNote = __Infer<typeof SharedNote>;

export const TranscriptChunk = __t.object("TranscriptChunk", {
  chunkId: __t.u64(),
  roomId: __t.u64(),
  source: __t.string(),
  text: __t.string(),
  startMs: __t.u64(),
  endMs: __t.u64(),
  sourceParticipantId: __t.option(__t.u64()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type TranscriptChunk = __Infer<typeof TranscriptChunk>;

