// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  nodeId: __t.u64(),
  title: __t.option(__t.string()),
  summary: __t.option(__t.string()),
  nodeType: __t.option(__t.string()),
  source: __t.option(__t.string()),
  urgency: __t.option(__t.string()),
  x: __t.option(__t.f64()),
  y: __t.option(__t.f64()),
};
