// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddAgentOutputReducer from "../add_agent_output_reducer";
import AddFindingReducer from "../add_finding_reducer";
import AddMapEdgeReducer from "../add_map_edge_reducer";
import AddSharedNoteReducer from "../add_shared_note_reducer";
import AddTranscriptChunkReducer from "../add_transcript_chunk_reducer";
import ClaimAgentTaskReducer from "../claim_agent_task_reducer";
import CompleteAgentTaskReducer from "../complete_agent_task_reducer";
import CreateAgentTaskReducer from "../create_agent_task_reducer";
import CreateMapNodeReducer from "../create_map_node_reducer";
import CreateQuestionCandidateReducer from "../create_question_candidate_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import SetRoomFocusReducer from "../set_room_focus_reducer";
import UpdateCursorReducer from "../update_cursor_reducer";
import UpdateMapNodeReducer from "../update_map_node_reducer";
import UpsertAgentWorkerReducer from "../upsert_agent_worker_reducer";
import UpsertParticipantReducer from "../upsert_participant_reducer";

export type AddAgentOutputParams = __Infer<typeof AddAgentOutputReducer>;
export type AddFindingParams = __Infer<typeof AddFindingReducer>;
export type AddMapEdgeParams = __Infer<typeof AddMapEdgeReducer>;
export type AddSharedNoteParams = __Infer<typeof AddSharedNoteReducer>;
export type AddTranscriptChunkParams = __Infer<typeof AddTranscriptChunkReducer>;
export type ClaimAgentTaskParams = __Infer<typeof ClaimAgentTaskReducer>;
export type CompleteAgentTaskParams = __Infer<typeof CompleteAgentTaskReducer>;
export type CreateAgentTaskParams = __Infer<typeof CreateAgentTaskReducer>;
export type CreateMapNodeParams = __Infer<typeof CreateMapNodeReducer>;
export type CreateQuestionCandidateParams = __Infer<typeof CreateQuestionCandidateReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type SetRoomFocusParams = __Infer<typeof SetRoomFocusReducer>;
export type UpdateCursorParams = __Infer<typeof UpdateCursorReducer>;
export type UpdateMapNodeParams = __Infer<typeof UpdateMapNodeReducer>;
export type UpsertAgentWorkerParams = __Infer<typeof UpsertAgentWorkerReducer>;
export type UpsertParticipantParams = __Infer<typeof UpsertParticipantReducer>;

